### ISSUE TITLE
Info Request (a little off topic): Acrostic jpz files?

### ISSUE THREAD

**Issue by dmurchie** [mrichards42/xword#115]
I don't seem to be able to find much about .jpz on the interwebs, but [found this from 9 years ago on Alex Boisvert's blog](https://alexboisvert.com/musings/2011/05/26/making-jpz-puzzles/).

So maybe these are dumb questions but:

1. Is a .jpz file the same as a CCW's xml output?
2. Is there any documentation on what an acrostic .jpz looks like?

I make an acrostic every two weeks using a homespun app that outputs printable PDFs and some proprietary json. I'd like to generate and offer compatible .jpz files.

Thanks,
David

**Comment by jpd236** [comment]
1. They seem to be the same, yep.

2. So the Acrostic JPZ files aren't technically standard JPZ files per the spec, since they rely on some features that aren't supported by normal JPZ files, as I understand it. As I understand it, Joon Pahk and Alex Boisvert made some minor extensions to the format so the Crossword Nexus web solver would support them. So we added the same support to XWord.

There's an example file at https://github.com/mrichards42/xword/files/4625993/Acrostic.for.Sunday.May.10.2020.zip (you have to unzip it to get to the JPZ). JPZ files are themselves ZIP files (though this is optional), so you have to unzip it again to see the underlying XML. Then you might want to put the XML through a pretty-printer like https://www.samltool.com/prettyprint.php to better view it.

Since you have a home-spun app - you might be interested in https://github.com/jpd236/kotwords/blob/master/src/jsMain/kotlin/com/jeffpdavidson/kotwords/model/Acrostic.kt, which generates the JPZ elements from somewhat simpler input. If you reach out to Joon, he also has a Perl script that he's using to do the same thing, and an example file in the intermediate input format (APZ) he's using.

Happy to answer questions about any of the above.

**Comment by dmurchie** [comment]
> example file at https://github.com/mrichards42/xword/files/4625993/Acrostic.for.Sunday.May.10.2020.zip

Jackpot. My solving app already expands the json from my builder to this exact same basic format (grid, cells, words, clues, etc.) with very minor differences (quote and meta data a little different). Unless there's some other magic I'm missing, zip the xml file, give it the jpz extension, and done.

Are the plans for an XWord v1.0?
Cool stuff - thanks!

**Comment by mrichards42** [comment]
> Are the plans for an XWord v1.0?

The version number is pretty arbitrary. The last one was 0.6.1 released in 2012, so I just bumped the minor version to 0.7.0 for this one -- I've mostly used the minor version for any new features or big changes and used the patch for bug fixes between minor versions. If I end up hearing that folks are turned off by not having a 1.0 I'd be happy to release the next one as 1.0, but otherwise :shrug:

**Comment by dmurchie** [comment]
The question really just goes to whether to post "jpz" with no instructions, or also direct people to your download page. And I have an audience of tens of people, so get ready ;)

It looks like the Mac app at least is unsigned (or whatever term Apple uses) so Mac OS X throws up a scary dialog on launch with two options: cancel, or cancel and move to trash ("developer could not be verified").

I think (?) that dialog used to give the option to authorize but now it just looks like something horrible is happening. And you have to know where to look in settings to authorize the app (there's no guidance in the warning dialog).

That being said, I repeat: really cool stuff! Glad I learned about your project.

**Comment by jpd236** [comment]
Yeah, I wonder if an instruction page on how to install the app might be warranted. On Mac, if I recall, the easiest way to deal with unsigned apps is to Control-Click on the application the first time you use it and select "Open", which should provide an option to allow opening the app. From then on it should work normally. On Windows, there are probably both unsigned warnings and Smart Screen warnings (which require clicking a subtle text link like "More info" to bypass). The main problem with signing (free) apps is cost: on Mac, it costs $100 per year; on Windows, it's hundreds+, especially if you want to bypass the Smart Screen warnings before enough people have downloaded and used the app. All in all, it's hard to consider it worth it when the app itself is free.

**Comment by dmurchie** [comment]
Having fooled with Xcode a bit, I immediately went to (OS X) Prefs > Security & Privacy to "allow" the app - though I'm sure there are easier ways to tell the machine to shut up and just run the thing.

Totally hearing you on the costs and hassle of getting your app signed/verified when distribution brings in no meaningful revenue - like, what's the point?

**Comment by crosswordnexus** [comment]
I feel like this issue can be safely closed
