### ISSUE TITLE
Segfault from rebus entry

### ISSUE THREAD

**Issue by yuvalwig** [mrichards42/xword#127]
I'm running Ubuntu 20.04, and got XWord to work. Pretty much everything seems to work ok, except that rebus entry causes a segfault and the program crashes. 

Specifically, when I press escape or insert or the rebus icon in the toolbar, the rebus entry square appears. I can type things in it without a problem, but when I hit enter, the program crashes. The terminal reads
```
(XWord:932314): GLib-GObject-WARNING **: 10:25:01.755: ../../../gobject/gsignal.c:2657: instance '0x7fe89c00a790' has no handler with id '6644594'
Segmentation fault (core dumped)
```
Here's the log generated by gdb: [trace.log](https://github.com/mrichards42/xword/files/5453978/trace.log). Any ideas for how to fix this?

**Comment by jpd236** [comment]
I was able to reproduce this, though I'm not really sure how to fix it properly. It only happens when you close the rebus dialog by pressing Enter/Return or Insert, e.g. when the window is destroyed in RebusTextCtrl::OnChar - it seems not to like it when the window is destroyed in the middle of processing a keypress.

This seems to work around the problem: https://github.com/jpd236/xword/commit/5efd9105ea0123c28655bb9bae7e8afd32f163ef

But I don't know enough about wxWidgets to know if this is really the proper way (and/or whether it's a bug in wxWidgets or in what we're doing) - defer to @mrichards42 on that one.

**Comment by yuvalwig** [comment]
This also fixed the bug for me—thanks so much!

I'll go ahead and close the issue for now, but it can be reopened if a less hacky fix is found :)

**Comment by mrichards42** [comment]
@jpd236 yeah, like you said, sounds like the problem is destroying the rebus window from inside its own event handler. I'm a little surprised this works on other platforms, but then wxWindow destruction is tricky. Looks like they added [`wxEvtHandler::CallAfter`](https://docs.wxwidgets.org/trunk/classwx_evt_handler.html#a63c7351618fd77330d80a250b3719519) in the last few years, which does basically the same thing you're doing in that commit.

So I think changing XGridRebusCtrl to trigger its own destruction like this would do the trick:

```c++
// where we call
m_grid->EndRebusEntry();
// instead
m_grid->CallAfter(&XGridCtrl::EndRebusEntry);
```

**Comment by jpd236** [comment]
Yep, that seems to work, although I had to explicitly pass true as the argument for it to compile. Sent along #130. At some point I'd like to land the broader set of changes needed to build on Linux - I could probably at least send a PR to get things to build, even though there are still some outstanding issues - but I'm not quite sure how to fix some of the output path issues and how we'd create a distributable version of things.
