### ISSUE TITLE
Filename with accent corrupted on save

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#133]
On Windows, I solved a puzzle with the file name `160-Olé.puz` ([link](https://www.davidalfredbywaters.com/s/160-Ole.puz)). When I saved the file, a new file was written with the name `160-OlÃ©.puz` and the original file left unchanged. Seems like the accent is getting mangled somewhere along the line.

**Comment by jpd236** [comment]
Doesn't seem to happen on Mac, FWIW.

**Comment by jpd236** [comment]
I'm pretty confused about how string representation works here given all the different libraries / types on the table, but it seems like the problem is in the converting between wxString and  std::string when passing the filename to the puz library to save. It doesn't happen if I just use wxString::ToStdString() to do the conversion, but I don't know if that's the "right" solution here. 

What might be going on is that we're assuming filenames should be UTF-8 strings, but in fact Windows might use UTF-16 when dealing with filenames (https://stackoverflow.com/questions/23393870/read-write-file-with-unicode-file-name-with-plain-c-boost).

**Comment by mrichards42** [comment]
Oof, yeah the encoding issues raised in that stackoverflow post ring a bell (specifically that Windows uses UTF-16 internally, and *nixes use UTF-8 internally). I was confused at first why the load/save code uses `std::string` instead of `puz::string_t` (which is `std::wstring` in every build I've used in years) . . . but then dug deeper to find that `std::ofstream` and all its variants only accept either `char *` or `std::string` as the file name arg, so I don't know what the right solution is either. And I expect that code ended up where it is now because I ran into this problem and didn't have any better ideas.

It sounds like there are windows APIs we could use to open a file with a unicode name, but I don't know that they use the standard streams interface, and adapting all the file-reading/writing code sounds rough, plus I think this might work differently in lua (IIRC most strings are converted to 8-bit as UTF-8 before handing off to lua as well).

> I'm pretty confused about how string representation works here given all the different libraries / types on the table, but it seems like the problem is in the converting between wxString and std::string when passing the filename to the puz library to save. It doesn't happen if I just use wxString::ToStdString() to do the conversion, but I don't know if that's the "right" solution here.

Reading the docs it sounds like using the wxString method could at least help in some cases, since it says it uses "current locale encoding". Sounds like we don't get full unicode support that way, but we'd at least get the most common accented characters.

**Comment by mrichards42** [comment]
> On Windows, I solved a puzzle with the file name 160-Olé.puz (link). When I saved the file, a new file was written with the name 160-OlÃ©.puz and the original file left unchanged. Seems like the accent is getting mangled somewhere along the line.

Here's what I'm confused about -- how were we able to _read_ that file but not write it?

. . . and in fact it looks like the conversion is different:

https://github.com/mrichards42/xword/blob/6a58f6fc939a5e7c17c85e514933c2170574cabb/src/MyFrame.cpp#L616

https://github.com/mrichards42/xword/blob/6a58f6fc939a5e7c17c85e514933c2170574cabb/src/MyFrame.cpp#L688-L690

So maybe try wx2file before wxString::ToStdString()?

https://github.com/mrichards42/xword/blob/811a30707515b0a3355cccd80917c33f8e7e6eea/src/utils/string.hpp#L25-L28
