### ISSUE TITLE
Barred iPuz files not rendering properly

### ISSUE THREAD

**Issue by boisvert42** [mrichards42/xword#174]
Some barred iPuz files (e.g https://crosswordnexus.com/downloads/barred_test.ipuz) do not render properly in XWord.  It should display as here: https://crosswordnexus.com/solve/index.html?file=/downloads/barred_test.ipuz but in XWord the bars are not respected.  XWord needs to know where the words start and end for barred crosswords, as that logic is needed to properly render this puzzle and others like it.

**Comment by mrichards42** [comment]
Ah, so the bars display, but the navigation is messed up because XWord can't figure out that the word is supposed to end at the bar? IIRC we've only actually tested bars in jpz files that have hard-coded "words", so it sounds like we need to have the auto-generated words algorithm handle bars in addition to black squares.

**Comment by boisvert42** [comment]
Yes, that's what I ended up doing and it worked fine.
