### ISSUE TITLE
Change direction with keyboard but stay on current square

### ISSUE THREAD

**Issue by WyrdByWord** [mrichards42/xword#198]
Is there a way to have direction change with the keyboard function the same way that direction changes on a second click does? The former changes directions and moves forward a square in the new direction. I would like to just change direction and stay in the same square without using the mouse.

**Comment by mrichards42** [comment]
Hi! Not quite. If you have "pause when switching direction" on (the default) arrow keys will do what you're asking but only if you're on a blank square. If you're on a square with a letter the arrow keys always move to the next square instead of staying on the same square. That preference is perhaps not worded very well.

There is an old PR #167 that would add an option to have the space bar do what you're asking but it isn't quite finished. If you wanted to give it a shot, the preferences dialog part is solid, but IIRC there's a little bit of work to do on the actual behavior.

**Comment by WyrdByWord** [comment]
Thank you. I did wonder what "pause when switching direction meant," so that is definitely useful to understand. Unfortunately, contributing code to implement this is way, way beyond my abilities! Since PR #167 is open, I will close this issue with this comment to avoid clutter.
