### ISSUE TITLE
0.8.0 release

### ISSUE THREAD

**Issue by mrichards42** [mrichards42/xword#200]
@jpd236 I'm thinking of cutting a release soon! I tagged [0.8.0-rc1](https://github.com/mrichards42/xword/releases/tag/0.8.0-rc1) this evening, the diff since your last PR is almost all lua stuff that I don't think you'd use since it's importers and downloaders, but if you know of any show-stopping bugs or have anything you'd like to get into a new release now's the time. FYI I might be convinced to do more frequent releases moving forward since the process isn't actually that hard 🙄

**Comment by jpd236** [comment]
Sounds great - both a release now and more frequent releases :)

I don't think I have anything in my immediate plans to work on. I'd love to make some progress on #178, since background colors and images are becoming more prevalent, but I'm not sure there are any easy fixes there. I also have been meaning to take a closer look at the issue we've been emailing about re: the clue column width being capped to a maximum when saving the layout, but I'm not too keen on digging deeper into the window management stuff.
