### ISSUE TITLE
Unable to open .puz with strange grid/clues

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#56]
The .puz file here:

http://bewilderingly.blogspot.com/2017/10/puzzle-50-mystery-theme-2.html

does not open in Xword with an error: "Clues do not match the grid"

It opens in regular across lite.

Since I haven't done the puzzle yet I haven't looked closely, but the blog post does seem to note something peculiar about the grid.

**Comment by mrichards42** [comment]
Interesting.  He's using `.` for black squares (normal) and `:` for missing squares (diagramless black squares). AL converts both of those to black squares since `:` is meaningless in a non-diagramless puzzle. I've allowed `:` to be a valid solution character, which is screwing up the grid numbering.

I don't have a concept of missing squares yet, and since puz doesn't either, it wouldn't make sense to convert `:` squares to missing squares here, so I think silently converting `:` to `.` in a non-diagramless puz file (like AL does) is the solution here.

**Comment by jpd236** [comment]
Thanks for taking a look! What you suggest sounds reasonable to me.

**Comment by jpd236** [comment]
FYI, the puzzles at https://nevillefogarty.wordpress.com/2018/07/20/now-we-are-six-times-five/ are also impacted by this.
