### ISSUE TITLE
Failed to run py2lua on fresh install

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#61]
This was reported externally:

Updating wxFB from python    C:\Program Files (x86)\XWord\scripts\xworddebug\wxFB.py
Failed!
C:\Program Files (x86)\XWord\scripts\xworddebug\py2lua.lua:226: attempt to index local 'f' (a nil value)
Updating wxFB from python    C:\Program Files (x86)\XWord\scripts\download\gui\wxFB.py
Failed!
C:\Program Files (x86)\XWord\scripts\xworddebug\py2lua.lua:226: attempt to index local 'f' (a nil value)

Two things to investigate here:

1) Why is it trying to regenerate? We moved to md5sum hashes of the input files instead of mtime which should have been enough, so something in the build process seems to be changing the input file from expectation.

2) Why is it failing to regenerate?

**Comment by mrichards42** [comment]
1. It looks like the [release](https://github.com/jpd236/xword/releases/tag/0.6.2-ci-alpha1) on your fork predates the [md5 commit](https://github.com/mrichards42/xword/commit/31068243813ff8c7ee33c358beb560db5164c0e2), so it's still using mtime.
1. I couldn't get it to fail, but I see that the `io.open` used to write the file [isn't wrapped in `assert`](https://github.com/mrichards42/xword/blob/f66aa4d1ef004822faf2c04620aaab87c6843e13/scripts/xworddebug/py2lua.lua#L224), so that script swallows the error. My best guess is that XWord doesn't (and shouldn't) have permission to write to Program Files directly.

**Comment by jpd236** [comment]
Hm, that was just a one-off test branch - I don't know if that was the build being used, since I linked to https://ci.appveyor.com/project/jpd236/xword/build/job/wvy9acc5r1l7rf49 which should have the commit. Should be easy enough to try to reproduce either way.

Good point about the file write failing though.

**Comment by jpd236** [comment]
I think this was resolved w/ the wxLua 3.0.0.6 drop. I fixed a bug there in the bit library which caused md5 to be calculated incorrectly on Mac, so the md5s I checked in were wrong and thus triggered recalculation on Windows. Everything should now be using the right md5s, and the xworddebug plugin is left out of release builds for distribution on Windows/Mac.
