### ISSUE TITLE
Support border styles

### ISSUE THREAD

**Issue by jpd236** [mrichards42/xword#66]
The American Values Club crossword from 7/11/18 is a labyrinth puzzle, where there is a snaking path throughout the whole grid. It's solvable in Xword, but really challenging because the labyrinth path isn't visible, especially if you have the "Move to Next Blank" movement style and some letters filled in.

http://www.crosswordnexus.com/solve/ renders the grid with thicker lines around the labyrinth path.

From a glance at the file, some \<cell\>s have top-bar="true" or left-bar="true".

(Also, notably, if you start solving the puzzle in XWord and then save it and try to move to http://www.crosswordnexus.com/solve/, it fails to open, so something about XWord's JPZ writing is incompatible, which would be interesting to investigate).

**Comment by mrichards42** [comment]
Too bad! That's definitely an extra challenge this puzzle probably doesn't need :) It also is impossible to read that super long clue in the prompt (though both crossword solver and the crosswordnexus solver have their own problems with that). It probably wants to have a minimum font size and a scrollbar.

I changed the issue title since I think it would be best to support border styles in general (ipuz has several styles as well). It's been a while since I've looked at the jpz spec though, so maybe this specific instance of thick borders would be easier to address only in jpz files.

**Comment by mrichards42** [comment]
On saving jpz files: crossword solver can open files saved by xword, but the crosswordnexus solver can't (though if you open an xword jpz in crossword solver, then save it, crosswordnexus *can* open it).

**Comment by jpd236** [comment]
FWIW, [Queer Qrosswords 2](https://queerqrosswords.com/) includes an ipuz cryptic crossword with borders which could be used to validate this support. That said, reading that file would be even more involved, since it uses the ipuz v2 spec and can't be opened at all; when manually adjusting the version to v1 to get the file to read, it loads, but the word locations are not determined correctly.
